### ISSUE TITLE
Не прописан обработчик ошибки пустого прокси при частых запросах

### ISSUE THREAD

**Issue by grkhr** [selesnow/getProxy#1]
> prox_ip_and_port <- getProxy(port = "3128", type = "http", country = "DE", supportsHttps = TRUE, action = "start")

Ger proxy from gimmeproxy.com
Error: {"status_code":429,"status_message":"Your request count is over the allowed limit of 10."}
, try get proxy from getproxylist.com
Ger proxy from getproxylist.com SUCCESS
IP port: :
Proxy server connection SUCCES

**Comment by selesnow** [comment]
Добрый день, спасибо, в ближайшие пару дней добавлю.
Тут смотрите в чём проблема, пакет работает с двумя сервисами, если в первом заканчивается квота из-за большого количества запросов он идёт на второй, а второй работает немного инае и возвращает пустой результат если не смог найти ничего под ваш фильтр, т.е. тут вам надо просто поменять фильтр или порт или страну другую, вы исчерпали квоту только на gimmeproxy.com, а на  getproxylist.com просто не нашлось прокси под ваш фильтрю

**Comment by selesnow** [comment]
В новой версии ошибка исправлена
