### ISSUE TITLE
Пакет перестал работать — проблема с API

### ISSUE THREAD

**Issue by IgorMaltsev** [selesnow/getProxy#2]
Алексей, добрый день. Сейчас при попытке использовать пакет вижу такую ошибку:

Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: certificate has expired
Ошибка: lexical error: invalid char in json text.
                                       Error in function (type, msg, a
                     (right here) ------^

**Comment by selesnow** [comment]
Готово, пакет полностью переписан на основе `httr`, ранее он был написан на базе `RCurl`.
