### ISSUE TITLE
Ошибка "Argument 'txt' must be a JSON string, URL or file."

### ISSUE THREAD

**Issue by IgorMaltsev** [selesnow/getProxy#3]
Алексей, добрый день. 
Указанная в заголовке ошибка начала появляется на некоторых странах (при этом тут же на других странах было все ок) после перехода пакета на httr. Но сегодня эта ошибка появляется постоянно (в том числе на тех странах, с которыми раньше было все ок). Пробовал с разницей в несколько часов — результат тот же.

Текст ошибки полностью:

Ger proxy from gimmeproxy.com
Ошибка: Argument 'txt' must be a JSON string, URL or file.

**Comment by selesnow** [comment]
Судя по всему у одного API закончились прокси, и при парсинге ответа от него такая проблема появилась.
Я ночью внёс некоторые исправления, попробуйте обновить пакет с GitHub.

**Comment by selesnow** [comment]
В новой версии проблему исправил.
